examenprep/www/MvcMovieDemo - UOW/MvcMovie/Models/ErrorViewModel.cs
namespace MvcMovie.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Models/Movie.cs
using System.ComponentModel.DataAnnotations;

namespace MvcMovie.Models
{
	public class Movie
	{
		public int MovieID { get; set; }
		[Display(Name = "Film Title")]
		public string Title { get; set; }
		[Display(Name = "Release Date")]
		[DataType(DataType.Date)]
		[DisplayFormat(ApplyFormatInEditMode = true,
		  DataFormatString = "{0:dd/MM/yyyy}")]
		public DateTime ReleaseDate { get; set; }
		public string Genre { get; set; }
		public int? Price { get; set; }
		public int RatingID { get; set; }

		public Rating? Rating { get; set; }
	}
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Models/Rating.cs
namespace MvcMovie.Models
{
	public class Rating
	{
		public int RatingID { get; set; }
		public string Code { get; set; }
		public string Name { get; set; }

		public ICollection<Movie>? Movies { get; set; }
	}
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Models/ViewModels/AddMovieViewModel.cs
namespace MvcMovie.Models.ViewModels
{
    public class AddMovieViewModel
    {
        public Movie Movie { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    }
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Models/ViewModels/ListMoviesViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MvcMovie.Models.ViewModels
{
	public class ListMoviesViewModel
	{
		public List<Movie> Movies;
		public SelectList Ratings { get; set; }
		public int ratingID { get; set; }
	}
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcMovie.Models;
using System.Diagnostics;

namespace MvcMovie.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MvcMovie.DAL;
using MvcMovie.Models;
using MvcMovie.Models.ViewModels;
using System.Data;

namespace MvcMovie.Controllers
{
	public class MoviesController : Controller
	{
        private IUnitOfWork _uow;

		public MoviesController(IUnitOfWork uow)
		{
            _uow = uow;
        }

		public IActionResult List(int ratingID = 0)
		{
			var listMoviesVM = new ListMoviesViewModel();

			if (ratingID != 0)
			{
				listMoviesVM.Movies = _uow.MovieRepository.Get(
					filter: m => m.RatingID == ratingID,
                    orderBy: m => m.OrderBy(x => x.Title)).ToList();
			}
			else
			{
                listMoviesVM.Movies = _uow.MovieRepository.Get(
                    orderBy: m => m.OrderBy(x => x.Title)).ToList();
            }

            listMoviesVM.Ratings =
                new SelectList(
                    _uow.RatingRepository.Get(orderBy: m => m.OrderBy(x => x.Name)).ToList(),
                    "RatingID", "Name");

            return View(listMoviesVM);
		}

        public IActionResult Details(int id)
        {
            var movie = _uow.MovieRepository.Get(
                filter: x => x.MovieID == id,
                includes: x => x.Rating).FirstOrDefault();

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
		{
			ViewData["Ratings"] =
				new SelectList(_uow.RatingRepository.GetAll()
				.OrderBy(r => r.Name),
							   "RatingID",
							   "Name");

			return View();
		}

        public IActionResult Add()
        {
            var addMovieVM = new AddMovieViewModel();
            addMovieVM.Movie = new Movie();
            return View(addMovieVM);
        }

        //POST: Movies/Add
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add([Bind("Movie,Code, Name")] AddMovieViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var rating = _uow.RatingRepository.Get
                        (filter: r => r.Code == model.Code && r.Name == model.Name).FirstOrDefault();

                    if (rating == null)
                    {
                        rating = new Rating { Code = model.Code, Name = model.Name };
                        _uow.RatingRepository.Insert(rating);
                    }

                    model.Movie.Rating = rating;

                    _uow.MovieRepository.Insert(model.Movie);
                    _uow.Save();

                    return RedirectToAction("List");
                }
            }
            catch (DataException)
            {
                ModelState.AddModelError("", "Unable to save changes.");
            }
            return RedirectToAction("Add");
        }
    }
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Controllers/RatingsController.cs
using System.Data;
using Microsoft.AspNetCore.Mvc;
using MvcMovie.DAL;
using MvcMovie.Models;

namespace MvcMovie.Controllers
{
    public class RatingsController : Controller
    {
        private IUnitOfWork _uow;

        public RatingsController(IUnitOfWork uow)
        {
            _uow = uow;
        }

        // GET: Ratings/List
        public IActionResult List()
        {
            return View(_uow.RatingRepository.GetAll());
        }

        // GET: Ratings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ratings/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("RatingID,Code,Name")] Rating rating)
        {
            if (ModelState.IsValid)
            {
                _uow.RatingRepository.Insert(rating);
                _uow.Save();
                return RedirectToAction("List");
            }
            return View(rating);
        }


        // GET: Ratings/Edit/5
        public IActionResult Edit(int id)
        {
            var rating = _uow.RatingRepository.GetByID(id);
            return View(rating);
        }

        // POST: Ratings/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("RatingID,Code,Name")] Rating rating)
        {
			if (ModelState.IsValid)
            {
                try
                {
                    _uow.RatingRepository.Update(rating);
                    _uow.Save();
                }
                catch (DataException)
                {
                    throw;
                }
                return RedirectToAction("List");
            }
            return View(rating);
        }

        // GET: Ratings/Delete/5
        public IActionResult Delete(int id)
        {
            _uow.RatingRepository.Delete(id);
            _uow.Save();
            return RedirectToAction("List");
        }
    }
}

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Main Menu";
}

<h2>Applying the repository pattern</h2>

<a asp-controller="Ratings" asp-action="List">All Ratings</a>
<br />
<a asp-controller="Movies" asp-action="List">All Movies</a>
<br />
<a asp-controller="Movies" asp-action="Add">Add Movies</a>

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Movies/Add.cshtml
@model MvcMovie.Models.ViewModels.AddMovieViewModel

@{
    ViewData["Title"] = "Add";
}
<form asp-action="Add">
    <table>
        <tr>
            <td><label asp-for="Movie.Title">@Html.DisplayNameFor(model => model.Movie.Title)</label></td>
            <td><input asp-for="Movie.Title" /></td>
        </tr>
        <tr>
            <td><label asp-for="Movie.Genre">@Html.DisplayNameFor(model => model.Movie.Genre)</label></td>
            <td><input asp-for="Movie.Genre" /></td>
         </tr>
        <tr>
            <td><label asp-for="Movie.ReleaseDate">@Html.DisplayNameFor(model => model.Movie.ReleaseDate)</label></td>
            <td><input asp-for="Movie.ReleaseDate" /></td>
        </tr>
        <tr>
            <td><label asp-for="Code">@Html.DisplayNameFor(model => model.Code)</label></td>
            <td><input asp-for="Code" /></td>
        </tr>
        <tr>
            <td><label asp-for="Name">@Html.DisplayNameFor(model => model.Name)</label></td>
            <td><input asp-for="Name" /></td>
        </tr>
        <tr>
            <td colspan="2"><input type="submit" value="Add" /></td>
        </tr>
    </table>
</form>

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Movies/Create.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Create";

    var ratings = (IEnumerable<SelectListItem>)ViewData["Ratings"];
}

<form asp-action="Create">

    <label asp-for="Title">@Html.DisplayNameFor(model => model.Title)</label>
    <input asp-for="Title" />
    <br />

    <label asp-for="RatingID">@Html.DisplayNameFor(model => model.Rating)</label>
    <select asp-for="RatingID" asp-items="ratings"></select>
    <br />

    <input type="submit" value="Create" />
</form>

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Movies/Details.cshtml
@model MvcMovie.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<dl>
    <dt>
        @Html.DisplayNameFor(model => model.Genre)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Genre)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Price)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Price)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ReleaseDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ReleaseDate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Title)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Title)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Rating)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Rating.Name)
    </dd>
</dl>

<br />
<br />
<a asp-controller="Home" asp-action="Index">Back to menu</a> 

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Movies/List.cshtml
@model MvcMovie.Models.ViewModels.ListMoviesViewModel

@{
    ViewData["Title"] = "All Movies";
}

<form asp-controller="Movies" asp-action="List" method="get">
    <select asp-for="ratingID" asp-items="Model.Ratings">
        <option value="0">-- Select a rating --</option>
    </select>
    <input type="submit" value="Filter" />
</form>

<br />

<table>
    <tr>
        <th>@(Html.DisplayNameFor(model => model.Movies[0].Title))</th>
        <th>@(Html.DisplayNameFor(model => model.Movies[0].ReleaseDate))</th>
        <th>@(Html.DisplayNameFor(model => model.Movies[0].Genre))</th>
    </tr>
    @foreach (var item in Model.Movies)
    {
        <tr>
            <td>
                <a asp-controller="Movies" asp-action="Details"
               asp-route-id="@item.MovieID">@(Html.DisplayFor(modelItem => item.Title))</a>
            </td>
            <td>@(Html.DisplayFor(modelItem => item.ReleaseDate, "{0:yyyy-MM-dd}"))</td>
            <td>@(Html.DisplayFor(modelItem => item.Genre))</td>
        </tr>
    }

</table>
<br/><br/>
<a asp-controller="Home" asp-action="Index">Back to menu</a> |
<a asp-controller="Movies" asp-action="Create">Create movie</a>
<br />

examenprep/www/MvcMovieDemo - UOW/MvcMovie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - Mvc Movie</title>
</head>
<body>
    <h1>Mvc Movie - @ViewData["Title"]</h1>
    <div>
        @RenderBody()
    </div>
</body>
</html>