FinalExercise 1/FinalExercise/FinalExercise/Models/ErrorViewModel.cs
namespace FinalExercise.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FinalExercise 1/FinalExercise/FinalExercise/Models/UpdateEnrollmentViewModel.cs
using FinalExercise.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace FinalExercise.Models
{
    public class UpdateEnrollmentViewModel
    {
        public string CourseName { get; set; }
        public SelectList StudentList { get; set; }
        public Enrollment Enrollment { get; set; }
    }
}

FinalExercise 1/FinalExercise/FinalExercise/Controllers/HomeController.cs
using FinalExercise.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FinalExercise.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FinalExercise 1/FinalExercise/FinalExercise/Controllers/QuestionController.cs
using FinalExercise.Data;
using FinalExercise.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace FinalExercise.Controllers
{
    public class QuestionController : Controller
    {
        private readonly SchoolContext _context;

        public QuestionController(SchoolContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var data = _context.Programmes.Include(p => p.Courses).ThenInclude(c => c.Enrollments).ToList();
            return View(data);
        }

        public IActionResult Course(int courseid)
        {
            var result = _context.Courses.Include(c => c.Enrollments)
                .ThenInclude(e => e.Student).Single(c => c.CourseId == courseid);

            return View(result);
        }

        public IActionResult UpdateEnrollment(int id)
        {
            UpdateEnrollmentViewModel vm = new UpdateEnrollmentViewModel();

            string courseName = _context.Enrollments
                .Include(e => e.Course).Single(e => e.EnrollmentId == id).Course.Name;

            var studentList = new SelectList(
                _context.Students, 
                "StudentId",
                "FullName"
                );

            var enrollment = _context.Enrollments.Find(id);

            vm.CourseName = courseName;
            vm.StudentList = studentList;
            vm.Enrollment = enrollment;
            return View(vm);
        }

        [HttpPost]
        public IActionResult UpdateEnrollment(UpdateEnrollmentViewModel model)
        {
            _context.Update(model.Enrollment);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

FinalExercise 1/FinalExercise/FinalExercise/Views/Question/Course.cshtml
@using FinalExercise.Data
@model Course

<h2>@Model.Name</h2>
<ul>
    @foreach (var enrollment in Model.Enrollments)
    {
        <li><a asp-controller="Question" asp-action="updateenrollment" 
            asp-route-id="@enrollment.EnrollmentId">@enrollment.Student.FullName</a></li>
    }
</ul>

FinalExercise 1/FinalExercise/FinalExercise/Views/Question/Index.cshtml
@using FinalExercise.Data
@model List<Programme>;

@foreach(var programme in Model)
{
    <h2>@programme.Name</h2>

    @foreach(var course in programme.Courses)
    {
        <li><a asp-controller="Question" asp-action="course" asp-route-courseid="@course.CourseId"> @course.Name</a> (@course.Enrollments.Count() enrollments(s))</li>
    }
}

FinalExercise 1/FinalExercise/FinalExercise/Views/Question/UpdateEnrollment.cshtml
@model UpdateEnrollmentViewModel

<h1>update enrollment</h1>
<p>@Model.CourseName</p>

<form asp-action="updateenrollment" method="post">
   <input type="hidden" asp-for="@Model.Enrollment.CourseId"/>
   <input type="hidden" asp-for="@Model.Enrollment.EnrollmentId"/>
   <select asp-for="@Model.Enrollment.StudentId" asp-items="@Model.StudentList"></select>

   <input type="submit" value="Save" />
</form>