MotoGP/Controllers/InfoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MotoGP.Data;
using MotoGP.Models;
using MotoGP.Models.ViewModels;
using System.Diagnostics;
using System.Xml.Linq;

namespace MotoGP.Controllers
{
    public class InfoController : Controller
    {
        private readonly GPContext _context;

        public InfoController(GPContext context)
        {
            _context = context;
        }


        public IActionResult ListRaces()
        {
            ViewData["BannerNr."] = 0;
            ViewData["Title"] = "Races";

            var Races = _context.Races;


            return View(Races.ToList());
        }

        public IActionResult BuildMap() 
        {
            var Races = _context.Races;

            ViewData["BannerNr."] = 0;

            return View(Races.ToList());
        }

        public IActionResult ShowRace(int id)
        {
            var Races = _context.Races.ToList();
            var race = Races[id];

            ViewData["id"] = id;
            ViewData["BannerNr."] = 0;
            ViewData["Title"] = "Race - " + race.Name;

            return View(race);
        }

        public IActionResult ListRiders()
        {
            ViewData["Title"] = "Riders";
            ViewData["BannerNr."] = 1;

            var Riders = _context.Riders.OrderBy(r => r.Number)
                .ToList();

            return View(Riders);
        }

        public IActionResult SelectRace(int SelectedRaceId)
        {
            ViewData["Title"] = "Races";
            ViewData["BannerNr."] = 0;

            SelectListRacesVM vm = new SelectListRacesVM();
            vm.RacesSelectList = new SelectList(
            _context.Races.OrderBy(r => r.Name).ToList(),
                "RaceID",
                "Name"
                );
            vm.SelectedRaceId = SelectedRaceId;

            if (SelectedRaceId == 0)
            {
                return View(vm);

            } else
            {
                vm.SelectedRace = _context.Races.Single(r => r.RaceID == SelectedRaceId);
                return View(vm);
            }
        }
    }
}

MotoGP/Views/Info/BuildMap.cshtml
@model IEnumerable<MotoGP.Models.Race>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    ViewData["Title"] = "Build Map";
}
<img src="~/images/banners/map.png" alt="map" usemap="#workmap"/>

<map name="workmap">
    @foreach (Race race in Model)
    {
        <a asp-controller="Info" asp-action="ShowRace" asp-route-id="1">
            <area class="circle" shape="circle" coords="@race.X,@race.Y,30">
        </a>
    }
</map>

MotoGP/Views/Info/ListRaces.cshtml
@model IEnumerable<MotoGP.Models.Race>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Races";
    var sortedRaces = Model.OrderBy(race => race.Date);
}

@for (int i = 0; i < sortedRaces.Count(); i++)
{
    Race race = sortedRaces.ElementAt(i);
    string month = race.Date.ToString("MMMM");

    if (i == 0 || month != sortedRaces.ElementAt(i - 1).Date.ToString("MMMM"))
    {
        <h3 class="fw-bold">@month</h3>
    }

    <div>
        @{var index = i + 1;}
        <p>@race.Date.ToString("dd/MM/yyyy") <a asp-controller="Info" asp-action="ShowRace" asp-route-id="@index">@race.Name</a></p>
    </div>
}

<div class="row">
    <a asp-controller="Home" asp-action="Menu">back</a> |
    <a asp-controller="Info" asp-action="BuildMap">Races on Map</a> |
    <a asp-controller="Info" asp-action="SelectRace">One by one</a>
</div>

MotoGP/Views/Info/ListRiders.cshtml
@model IEnumerable<MotoGP.Models.Rider>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@foreach (Rider rider in Model)
{
    <div>

        @{
            var imagePathRider = Url.Content($"~/images/riders/{rider.Number}.jpg");
            var imagePathFlag = Url.Content($"~/images/flags/{rider.CountryID}.png");
        }
        <img src="@imagePathRider" alt="rider pic" />
        <img src="@imagePathFlag" alt="flag pic" />
        <h2 class="text-opacity-25">@rider.Number</h2>
        <h5>@($"{rider.FirstName} {rider.LastName}")</h5>

    </div>
}

MotoGP/Views/Info/SelectRace.cshtml
@using MotoGP.Models.ViewModels
@model SelectListRacesVM;

@{var imagePath = Url.Content($"~/images/races/{Model.SelectedRaceId}.jpg");}


<form asp-controller="Info" asp-action="SelectRace" method="get">
    <select asp-for="SelectedRaceId" asp-items="Model.RacesSelectList">
        <option value="0">-- select a race --</option>
    </select>
    <input type="submit" value="submit"/>
</form>


@if (Model.SelectedRaceId != 0)
{
    <img src="@imagePath" alt="Circuit" />
    <p>@Model.SelectedRace.Description</p>
}

MotoGP/Views/Info/ShowRace.cshtml
@model MotoGP.Models.Race

@{
    var id = ViewData["id"];
    Layout = "~/Views/Shared/_Layout.cshtml";
    var imagePath = Url.Content($"~/images/races/{id}.jpg");
}

<h2>@Html.DisplayFor(model => model.Date) - @Html.DisplayFor(model => model.Country)</h2>
<img src="@imagePath" alt="circuit" />
 <p>@Html.DisplayFor(model => model.Description)</p>